### ISSUE TITLE
Integrate LTI Provider with VideoFront

### ISSUE THREAD

**Issue by procangroup** [openfun/videofront#6]
The objective is to integrate the LTI Provider module in the VideoFront code. These are the different steps:

- Modify and integrate the LTI Provider module (https://github.com/Harvard-ATG/django-app-lti)

- Import the modified LTI Provider module into the VideoFront code  (resolve python compatibility problem)

Test:

- Deploy an LTI consumer xblock in LMS 
- Launch an LTI request
- Verify authentication
- URL Redirection from LTI to VideoFront interfaces (for the first test, just display the html page api/v1/playlists)

**Comment by jmaupetit** [comment]
Didn't know about ghost accounts...
